### ISSUE TITLE
No such file or directory: 'src/data/papers_pdf/'

### ISSUE THREAD

**Issue by xge** [fabian-beck/survis#8]
When running survis this error message appears:

````shell
$ python update_data.py
detected change in bib file
convert bib file
list available paper PDF files
Traceback (most recent call last):
  File "update_data.py", line 95, in <module>
    update()
  File "update_data.py", line 85, in update
    listAvailablePdf()
  File "update_data.py", line 59, in listAvailablePdf
    for file in os.listdir(papersDir):
FileNotFoundError: [Errno 2] No such file or directory: 'src/data/papers_pdf/'
````

**Comment by shivam-agarwal** [comment]
A similar problem which you encountered before where Git does not let you add empty directories to the project.

**Comment by xge** [comment]
A common workaround for this is to add empty `.gitkeep` files to the directories. See #10
